# Generated by Django 3.2.4 on 2021-07-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('TikTok', 'TikTok')], max_length=15)),
                ('followersnumber', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
