# Generated by Django 3.2.4 on 2021-07-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggers',
            name='profile_link',
            field=models.URLField(default='https:/'),
        ),
    ]
