# Generated by Django 3.2.4 on 2021-07-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bloggers_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggers',
            name='profile_link',
            field=models.URLField(default='https:/instagram.com/ (tiktok.com/@)'),
        ),
    ]
