# Generated by Django 3.2.4 on 2021-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_bloggers_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggers',
            name='followersnumber',
            field=models.IntegerField(max_length=12),
        ),
    ]
