# Generated by Django 3.2.4 on 2021-07-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_bloggers_followersnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggers',
            name='followersnumber',
            field=models.IntegerField(),
        ),
    ]
