# Generated by Django 3.2.4 on 2021-07-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bloggers_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='zayavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
