# Generated by Django 3.2.4 on 2021-07-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_zayavki'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavki',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
